/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.minidsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MiniDslRuntimeModule extends AbstractMiniDslRuntimeModule {
}
