/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.minidsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MiniDslStandaloneSetup extends MiniDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MiniDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
